### ISSUE TITLE
LCD Data & Web Interface Show Different Domain Numbers

### ISSUE THREAD

**Issue by gh0stshell** [jacobsalmela/pi-hole#200] opened 2016-01-19 20:03 UTC
My LCD domain numbers do not match what shows in the web interface by 60K.

LCD Domains: 130K
Web Interface Domains: 65K

**Comment by dschaper** [comment] 2016-01-19 20:33
I think there are some changes coming up with `chronometer.sh` and we'll see if the problem persists when the updates are added in. I'm still waiting for my display to come in so I can help test out this aspect of the project.

**Comment by PromoFaux** [comment] 2016-01-19 21:00
Ah, the issue is already here.. The `chronometer.sh` changes have already been merged, along with the changes to the website.

@gh0stshell Any chance you could run the install script, and then try again?

**Comment by PromoFaux** [comment] 2016-01-19 21:02
No wait, don't. There is a bug

I'll look into it

**Comment by PromoFaux** [comment] 2016-01-19 21:16
Fixed in PR #201 .

I had forgotten to check if current installation was using IPv6 or not before calculating the total domains to display on the LCD.

**Comment by gh0stshell** [comment] 2016-01-20 00:41
I am reinstalling completely in about 30min so I will test when done.

**Comment by PromoFaux** [comment] 2016-01-20 00:55
Fix isn't merged yet, but when it is it will work

**Comment by gh0stshell** [comment] 2016-01-20 01:01
I am downloading Jessie with the adafruit drivers. If I can just replace the chrono script with the new one that works for me.

**Comment by dschaper** [comment] 2016-01-20 01:16
I would try just updating that one script first. (You may want to just run the `curl` command, it will grab the latest versions of everything. You shouldn't need to reflash the SD Card all the time, although you will need to this one last time since you are changing from Rasbian Jessie to the AdaFruit Jessie with their extentions.

**Comment by jacobsalmela** [comment] 2016-01-20 01:38
I can confirm the change in #202 fixes this issue.

**Comment by dschaper** [comment] 2016-01-20 01:39
Okay, is it ready for master?

**Comment by jacobsalmela** [comment] 2016-01-20 01:40
Yes.

**Closed** 2016-01-20 01:42 UTC
Labels: bug, question
